apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ise-shop-prod
type: Opaque
stringData:
  POSTGRES_USER: onlineshop_user
  POSTGRES_PASSWORD: onlineshop_pass
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  JWT_SECRET: prod-change-me
