apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: onlineshop
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/onlineshop_db
  SPRING_DATASOURCE_USERNAME: onlineshop_user
  SPRING_DATASOURCE_PASSWORD: onlineshop_pass
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
